### PR TITLE
WIP — switch to Vue 3

### PR DESCRIPTION
**Pull request by janniks**
🚧

### CODE REVIEW

**Comment by rashidpathiyil** [comment]
Really excited to see this update 🎉

**Comment by rashidpathiyil** [comment]
@janniks What happened to this PR? 🫠

**Comment by janniks** [comment]
🙈 Have you tried the alpha?

**Comment by janniks** [comment]
yo, made some progress today -- thanks for the bump.

I believe `vue-notion@3.0.0-beta.1` is working, so I pushed it to main and released. Still marking as `beta` for now until the first folks switch. 🙌

**Pull request merged**
